# source: https://packaging.python.org/appveyor
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "pypy"
    - TOXENV: "pypy3"

matrix:
  allow_failures:
    - TOXENV: "pypy3"  # pytest + pypy3 + windows raises; maybe open an issue?

install:
  - ps: |
      if ($env:TOXENV -eq "pypy") {
          (New-Object Net.WebClient).DownloadFile('https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.1.1-win32.zip', "$env:appveyor_build_folder\pypy2.7-v7.1.1-win32.zip")
          7z x pypy2.7-v7.1.1-win32.zip -oc:\
          $env:path = "c:\pypy2.7-v7.1.1-win32;$env:path"
      } elseif ($env:TOXENV -eq "pypy3") {
          (New-Object Net.WebClient).DownloadFile('https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.1.1-win32.zip', "$env:appveyor_build_folder\pypy3.6-v7.1.1-win32.zip")
          7z x pypy3.6-v7.1.1-win32.zip -oc:\
          $env:path = "c:\pypy3.6-v7.1.1-win32;$env:path"
      }
  - "py -3.6 -m pip install poetry tox tox-appveyor --upgrade"
  - "py -3.6 -m pip install toml setuptools-scm --upgrade"
  - "py -3.6 travis\\setversion.py"
  - "SET PATH=C:\\Python36-x64\\;C:\\Python36-x64\\Scripts;%PATH%"

build_script:
  - "poetry build -vvv --no-interaction --format=wheel"

test_script:
  - "tox -vv"

artifacts:
  - path: dist\*.whl

on_finish:
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
      $LastExitCode = 0
