# source: https://packaging.python.org/appveyor
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - TOXENV: "pypy3"
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py38"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py38"
      TOX_APPVEYOR_X64: 0

matrix:
  allow_failures:
    - TOXENV: "pypy3"  # pytest + pypy3 + windows raises; maybe open an issue?

install:
  - ps: |
      if ($env:TOXENV -eq "pypy3") {
          (New-Object Net.WebClient).DownloadFile('https://downloads.python.org/pypy/pypy3.7-v7.3.2-win32.zip', "$env:appveyor_build_folder\pypy3.7-v7.3.2-win32.zip")
          7z x pypy3.7-v7.3.2-win32.zip -oc:\
          $env:path = "c:\pypy3.7-v7.3.2-win32;C:\pypy3.7-v7.3.2-win32\bin;$env:path"
          pypy3 -m ensurepip
          New-Alias python c:\pypy3.7-v7.3.2-win32\pypy3.exe
      } else {
          $env:Path = "C:\Python36-x64\;C:\Python36-x64\Scripts;$env:Path"
      }
  - ps: python -m pip install pip poetry setuptools-scm tox tox-appveyor --upgrade
  - ps: $VERSION = & python -c "import setuptools_scm; print(setuptools_scm.get_version())"
  - ps: poetry version $VERSION

build_script:
  - ps: poetry build -vvv --no-interaction --format=wheel

test_script:
  - ps: tox -vv

artifacts:
  - path: dist\*.whl

on_finish:
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
      $LastExitCode = 0
