# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: []
        files: ^.*.pyi?$  # format .py and .pyi files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-logging-format, flake8-builtins, flake8-eradicate, flake8-fixme, pep8-naming, flake8-pep3101, "git+https://github.com/best-doctor/flake8-annotations-complexity.git@3863739c34748db8fb5a740d903b8e243dfddb20"]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        additional_dependencies: ["isort[pyproject]"]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
        exclude: tests/
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "poetry run mypy"
        language: system
        exclude: tests/.*.py
        types: [python]
        pass_filenames: false
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    -   id: doc8
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
    -   id: rst-backticks
