# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    skip:
    -   pytype  # does not support py3.11 yet

repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.269
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types: []
        files: ^.*.pyi?$
        exclude: ^_typeshed/
    -   id: ruff
        name: ruff (typeshed)
        types: []
        files: ^_typeshed/.*.pyi?$
        args: [--fix, --exit-non-zero-on-fix, --config=_typeshed/pyproject.toml]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        types: []
        files: ^.*.pyi?$
        exclude: ^_typeshed/
    -   id: black
        name: black (typeshed)
        types: []
        files: ^_typeshed/.*.pyi?$
        args: [--config=_typeshed/pyproject.toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-docstrings==1.6.0
        -   flake8-fixme==1.1.1
        -   flake8-pep3101==1.3.0
        -   flake8-annotations-complexity==0.0.7
        -   flake8-pyproject==1.2.2

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: tests/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/hoefling/pre-commit-pytype
    rev: 2023.4.27
    hooks:
    -   id: pytype
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/fsouza/pre-commit-pyre-check
    rev: v3-0.9.10
    hooks:
    -   id: pyre-check
        entry: pyre check
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
    -   id: doc8
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
