# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: []
        files: ^.*.pyi?$  # format .py and .pyi files
        exclude: ^_typeshed/
    -   id: black
        name: black (typeshed)
        types: []
        files: ^_typeshed/.*.pyi?$  # format .py and .pyi files
        args: [--config=_typeshed/pyproject.toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-logging-format, flake8-builtins, flake8-eradicate, flake8-fixme, pep8-naming, flake8-pep3101, flake8-annotations-complexity]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        exclude: tests/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/hoefling/pre-commit-pytype
    rev: 2021.8.24
    hooks:
    -   id: pytype
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/fsouza/pre-commit-pyre-check
    rev: v2-0.9.3
    hooks:
    -   id: pyre-check
        entry: pyre check
        exclude: tests/.*.py
        types: [python]
        additional_dependencies: [devpi-client,keyring]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    -   id: doc8
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: rst-backticks
