dist: xenial
language: python
os:
- linux
env:
  global:
  - _latest=3.7
  - secure: UD0wGrxyq4ytUWQ3utezLmAxNEJWma0Dhk3Q51/UwdtSzsvYGOj3YNOxdTV/h6I3OumjG8YizxQoxSdUns33OYo48tPvGtyyI+QEMkZLI6+k4ufZopF0U1D/nyHTBNKztFSRrz/tZ7Fp7SaC2jZeSJelG5+6CiJqCGy3xCWSaPXQId0AyJS12iNI7NVGm0iH2/ExtUL/bBkBu9sNkg1hAWr24hPQxryZ5MMIcDwxEVhochc9cD+Ks4N5HPjQzM6yFkugV95+050czw0huR4v3B1WHpfSY0wy7FW5e0UokftEKQl+5jtxJIs8qUCNY21ahXYKh2AKEzdHYXGqMwqH+um2Sd4lL2bZdtFGnBU4MS8u8HfsNqNd0gqxVygq0ixB5E8PaFnuO4r1xqzbHbmbNTUhULLgf7fa/GT802HB53vyD1TJFBUaBsfhUblqBKzGVJSZdXTNZ2qZLO9uMyyKDNdFDNnHHXuO+gHlUcGWzJ4KYcqV/f+3v7q9ECy/0Fqb9yRz8ws8UVLJvUqWS5BQqoQ9zkq2Z4ncndIQtGYmL1In75ofoq94AMRTs45RqPB4AjoIOlI17DkWWegpX/oO+LOBrJiet7mkl7KnmoRR0HlGHhH8KLTGli6DGQozNVmyYa3JzocWWA+GzIKgQnK9KI+w8QYJjeYn/QuhliQ3EMY=
python:
- 3.5
- 3.6
- 3.7
- 3.8
- "nightly"
- pypy3
# osx builds, see https://github.com/travis-ci/travis-ci/issues/2312
# osx builds take too long on travis, turning off for now
#matrix:
#    include:
#        # python2 preinstalled on osx
#        - os: osx
#          language: generic
#        # latest python2 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python
#        # latest python3 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python3
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ -n "$_osx_install" ]; then
          brew update && brew install "$_osx_install"
      fi
  fi
install:
# workaround for poetry missing setuptools-scm support
- pip install "poetry>=1.0" --upgrade
- poetry run pip install tox tox-travis setuptools-scm --upgrade
- poetry version $(poetry run python -c "import setuptools_scm; print(setuptools_scm.get_version())")
script:
- poetry run tox
after_success:
- rm -rf dist/
- poetry build -vvv --no-interaction --format=wheel
deploy:
  - provider: releases
    cleanup: false
    skip_existing: true
    token:
      secure: Iozor2chzNMOHeFYXwOn0hIeA5V/pHXVgesyoUYGPhDX9DtcpqjfekBxV/rd3vv0oOD4PuNBeNZPKxAcemVeyIq3UFilce7t644bwHSjbybqCmN0gEJTPFdf++PsxJi1kuVhvnWHknWhv48FIT370DmJBpf+K2TK49rgxsTLEHvdlTx7JnFThdOOIx8mz4b0xmhJB+sxQ3gRChZBxcRAlljIDYEodyJ4sdGXQbht7RLk9Zp1AsDuwTbrDqp3wqPu17VRT01OtE4YgFZDpT2ph5+U8w6zurG6xGpXMKMQZNOJ4YbuIFEIFF2kpPeOAegx8jAZIeBhDdh0fGoTtTfCDNc8I9tfSDg5ClW5hmDutaTKF9qfdIAtIQGYz/wB4q6O0f435FfFZioKEOGFxNeR1p4+XvGIjuaeQTotgyEC/4ghWt3Ce4N+A0E6Xo1DrcI5hXUTT55LtBSrmgmBU5eHr60iucEE0shI0mo83hVP67xrpDJImuJa/FlvtYVUo59JuU1Ecd/PPnfg6QEuLOAzrw0dsIT2C9rwkIV357OiZ/ZDvCWgBye/ROsYZGLakauBuUgwZqdTX1NdrTWD9zeNK+JpZK654Df04c41qGM9RDYLVK1bJreVmZC7DaXYeogvDTqYoTTc56uP3qLchrRbyW8Q7xdt7Ha8XMDsMbXONmc=
    file_glob: true
    file: dist/*.whl
    on:
      tags: true
      repo: hoefling/devpi-client-extensions
      condition: "$TRAVIS_PYTHON_VERSION == $_latest"
  - provider: pypi
    cleanup: false
    skip_existing: true
    username: hoefling
    password:
      secure: HSEQAMClJz0yO7TKF6gYxPy7y/JfAT6IRGrpebx4Vj31kBFUGhKPYuR9uniPBiVe6vr/qsJC2oNPAHDp+J/hs+MKblmmIMiL/Zxtum68UuOKxsuq2LbfYtgeqtz8j2AbJKBwhxhGTCgk2L8IKi57uqzQqv98GAJc2sK6Vf5Jz15b927X/iINacVQDJuBoiSK6JI5/7FMdPiAgy+mdmgnTLsay0CNk3A712q/gTtTl9PEhCi6cybiY8Xy37NDmG8EGWjFjh9ObhYO5rvsZ/aDf9/lZLDoUC/loxVQD1vy0DxNrwCZd1P5AYobTbwOGqXEarck+qmQuiyjyQBYE+z6kY1wEVc6J0QM+aaMlS1wCwsKNF6SAddRn2Sia04i/PKnwRZ/OP+e7r3GMvOkYro+Hg625oTCnMu7c1E+V8GLJim2mhdyoZ+54lm6yB/N/oMuUi3oJsb+WtzeXITMqUTWhnvkwzcDQMOpIfejpRqTsY7k9d2wl8zS6GETbQeZ7+RLwyx4syzxP+RZvpMBmOXuN9P6T7aWKo4UrZbYZjdIYOhsMkyvgvqxL2mEgZxCp2odLAd1KhmmD0IRIeyDdLGhxPXZaPMH8nznA5afjD6LUjVnLa1AZbvaa8D3xmvjTPXqqF0xJiWhiHp6XdsWzYbCLyzYzH5n2aIC0PNmHtFOIuY=
    distributions: bdist_wheel
    on:
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION == $_latest"
