language: python
os:
- linux
env:
  global:
  - _latest=3.6
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
matrix:
  allow_failures:
    - python: 3.7-dev
    - python: nightly
# osx builds, see https://github.com/travis-ci/travis-ci/issues/2312
# osx builds take too long on travis, turning off for now
#matrix:
#    include:
#        # python2 preinstalled on osx
#        - os: osx
#          language: generic
#        # latest python2 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python
#        # latest python3 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python3
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ -n "$_osx_install" ]; then
          brew update && brew install "$_osx_install"
      fi
  fi
  # prepare test coverage for latest python version only
  if [ "$TRAVIS_PYTHON_VERSION" == "$_latest" ]; then
      pip install python-coveralls
  fi
install:
- pip install pipenv --upgrade
- pipenv install --dev --skip-lock
- pipenv check
script:
- pipenv run python setup.py test flake8 bdist_wheel
after_success:
- |
  if [ "$TRAVIS_PYTHON_VERSION" == "$_latest" ]; then
      coveralls
  fi
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: lfoVhw3l33gVOb7p0C7dvxZmRAi3T94iZTrcuSaerIR1TCMJWJ9IPPFPwD67UqNBB59Wjefl4PhuemWXYgtKiDOHAC4qihVVww9n/Fn8Y5M8vK2aiU97+IUzSqfQsQZQKo0yPb0dmROtrGOJYrODoV9H0dbs624M0Q0/oKK4B83N4cs7M93iXLkPfjDOCfUhcqBSlCpuUt9g1Yr6xjObmUXDVhrNDZNzmasajOFDpHQthFEZobK1abvW3ceLvuw0FzC5fZaFgbNZkRXBwQN1kTSezJa9bicnTDoAetAp0+J0yTGn6huCFYv9G8KwIWIqEIi4qclX+nhQxx+cV5D6OnxTt5AmmslrvAg72FNt2jv7eY/q8eCTswlqNzkHrVp4RDzZMiyky3U8OJIZwcf7A7L1V/M1vkwNHUYbihmZl7Yra/itYq213ZWYkRIlShnwSlhMKjJpS0egoBNcb7uMSPsFAMIehtfnk0p0F92l2VaE0M9nFzPU9iKAmxkab0I+cfzQK/q4oTZZhuPZ9eFjFV/xo3rJ7+mbo7Zb3pYwvPYT9LfjWmhpFtLrKMAMJ4wiqcqDhRVG7s75GcwaJcrvm+7FiyFfnninWjyQol8SGyCIA2as92o1OfY5SqIA4O3GmOsHNdJyqhWAY6RWSLRGIZKzgDIZe29W4RE6I+gvmlA=
    file_glob: true
    file: dist/*.whl
    on:
      tags: true
      repo: hoefling/devpi-client-extensions
    condition: $TRAVIS_PYTHON_VERSION == $_latest
  - provider: pypi
    skip_cleanup: true
    user: hoefling
    password:
      secure: oZ6MdoOz+mLDusZQGCK7nDdnVN3rh5vWXbm3lwJWLfQ0WfvsLW6NxXFB0vNGpcKCNHgaxbahqPHUpkzOJcAHqi+SyNiXUT3aFV+lGKZMaUhMdhLNI6hEwrUElM2fq3ELxMNrUFVFD2kx6AAOTdsdtMf3LCo6Z1xXPoOGZqylMDUVAkgc/2ij6ZfstzCGS1wS7Xsmnd5yFGzzlj0CO1Ystgdp0cDB2mD6qTslzf39BzyNpwHYlgt7BOYvLzH7yoHc+Mgpy6EfERrt+I7SfPf/4VFcpGLKSNEGw0c2wyc4aLSs/UpHoOhHwMaY6xC0yqLXu/kb81f3GfyVj7B+IkJiwDMJ2xu6n4kfVSohmsL21UIicJaBesapj77z+3YLSsYhjJstzbI6bJoKrnl49xNbrdgXO+299Rzrm3pb2XFw0t/7lnvRTkXPOHiBc21bocVsV19U9N2EeDqYXQyTsT09y2pwvBZLD3qaR1QIuQPGJZo6fxvdFcCcwFeHEEsaSEEINtanCwZHFFWAaqSwanpHGA4NbYpmrNLn24/gbDu650eG0Qj2biYCZTFUATn7wCS5k7avJUDhFHNtg3O1aDVeJ9pdN/P+ThqLs0DnbSg5//URS6IeOQZ0GAj6PFT4PSwVpmPHvkuSxeIwsMxBiJVD98F2TmpqVRkWCzIrDM6LAjQ=
    distributions: bdist_wheel
    on:
      tags: true
    condition: $TRAVIS_PYTHON_VERSION == $_latest
