language: python
os:
     - linux
env:
     global:
         - _latest=3.6
python:
     - 2.7
     - 3.4
     - 3.5
     - 3.6
# osx builds, see https://github.com/travis-ci/travis-ci/issues/2312
# osx builds take too long on travis, turning off for now
#matrix:
#    include:
#        # python2 preinstalled on osx
#        - os: osx
#          language: generic
#        # latest python2 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python
#        # latest python3 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python3
before_install:
    - |
        if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            if [ -n "$_osx_install" ]; then
                brew update && brew install "$_osx_install"
            fi
        fi
        # prepare test coverage for latest python version only
        if [ "$TRAVIS_PYTHON_VERSION" == "$_latest" ]; then
            pip install python-coveralls
        fi
install:
    # runtime dependencies
    - pip install devpi-client
    # test dependencies
    - pip install pytest-runner pytest-cov pytest-mock
    # static code analysis
    - pip install flake8
script:
    - python setup.py test flake8 bdist_wheel
after_success:
    - |
        # run test coverage for latest python version only
        if [ "$TRAVIS_PYTHON_VERSION" == "$_latest" ]; then
            coveralls
        fi
