dist: xenial
language: python
os:
- linux
env:
  global:
  - _latest=3.9
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
- "nightly"
- pypy3
# osx builds, see https://github.com/travis-ci/travis-ci/issues/2312
# osx builds take too long on travis, turning off for now
#matrix:
#    include:
#        # python2 preinstalled on osx
#        - os: osx
#          language: generic
#        # latest python2 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python
#        # latest python3 from homebrew
#        - os: osx
#          language: generic
#          env:
#              - _osx_install=python3
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ -n "$_osx_install" ]; then
          brew update && brew install "$_osx_install"
      fi
  fi
install:
# workaround for poetry missing setuptools-scm support
- pip install "poetry>=1.0" --upgrade
- poetry run pip install tox tox-travis setuptools-scm --upgrade
- poetry run task scm | xargs poetry version
script:
- poetry run tox
after_success:
- rm -rf dist/
- poetry build -vvv --no-interaction --format=wheel
