# source: https://packaging.python.org/appveyor
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 0

install:
  - "py -3.6 -m pip install poetry tox tox-appveyor --upgrade"
  - "py -3.6 -m pip install toml setuptools-scm --upgrade"
  - "py -3.6 travis\\setversion.py"
  - "SET PATH=C:\\Python36-x64\\;C:\\Python36-x64\\Scripts;%PATH%"

build_script:
  - "poetry build -vvv --no-interaction --format=wheel"

test_script:
  - "tox -vv"

artifacts:
  - path: dist\*.whl

on_finish:
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
      $LastExitCode = 0
