# source: https://packaging.python.org/appveyor
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
 # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # Python 3.4 has setuptools==18.2 by default that is unable to install pipenv
  # flake8 needs typing backport for python<3.5
  - 'if "%PYTHON_VERSION%" == "3.4.x" (
        pip install --upgrade setuptools typing
    )'
  - "pip install wheel pipenv"
  - "pipenv install --dev"

  # TODO: for some reason, PEP 508 env markers are not installed completely
  # colorama is required by pytest on windows
  - "pipenv run pip install colorama"
  # pathlib2 is required for python<3.6
  - "set pre36=false"
  - 'if "%PYTHON_VERSION%" == "2.7.x" set pre36=true'
  - 'if "%PYTHON_VERSION%" == "3.4.x" set pre36=true'
  - 'if "%PYTHON_VERSION%" == "3.5.x" set pre36=true'
  - 'if "%pre36%" == "true"  (
        pipenv run pip install pathlib2
    )'

  # running pytest==3.5 fails on Python 2.7 because of missing funcsigs and mock
  # running flake8 fails on Python 2.7 because of missing configparser, enum34 and functools32
  - 'if "%PYTHON_VERSION%" == "2.7.x" (
        pipenv run pip install funcsigs mock configparser enum34 functools32 typing "more-itertools<6.0.0,>=4.0.0"
    )'
  # end TODO
  - "pipenv run pip list"
  - "pipenv check"

build_script:
  - "pipenv run python setup.py bdist_wheel"
  - "pipenv run pip uninstall -y devpi-client-extensions"  # remove the editable install
  - "pipenv run pip install devpi-client-extensions --find-links dist"
  - "pipenv run python setup.py clean"

test_script:
  - "pipenv run pytest"

after_test:
  - "pipenv run python setup.py flake8"

artifacts:
  - path: dist\*.whl

on_finish:
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
      $LastExitCode = 0
